# Generated by Django 4.1.2 on 2022-11-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='branches',
            options={'managed': False},
        ),
    ]
