# Generated by Django 4.1.2 on 2022-11-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_banks_options_alter_branches_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banks',
            table='banks',
        ),
        migrations.AlterModelTable(
            name='branches',
            table='branches',
        ),
    ]
